services:
  # Backend Flask Python Web Service
  - type: web
    name: talentiq-backend
    env: python
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn -c gunicorn.conf.py wsgi:app
    envVars:
      - key: FLASK_APP
        value: app
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
        placeholder: "postgresql://username:password@host:5432/talentiq"
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
